//
//  Constants.swift
//  WorkoutTracker
//
//  Created by Koctya on 11/13/15.
//  Copyright © 2015 Koctya Bondar. All rights reserved.
//

let EXRS_STATE_NOT_LOAD = 0;
let EXRS_STATE_IS_LOADING = 1;
let EXRS_STATE_LOADED = 2;


//STRINGS



let str_Workouts = NSLocalizedString("str_Workouts", comment:"")
let str_NameNewWorkout = NSLocalizedString("str_NameNewWorkout", comment:"")
let str_Cancel = NSLocalizedString("str_Cancel", comment:"")
let str_CreateWorkout = NSLocalizedString("str_CreateWorkout", comment:"")
let str_PlsInpWorkoutName = NSLocalizedString("str_PlsInpWorkoutName", comment:"")
let str_PlsInpExerName = NSLocalizedString("str_PlsInpExerName", comment:"")
let str_NoWeight = NSLocalizedString("str_NoWeight", comment:"")

let str_Close = NSLocalizedString("str_Close", comment:"")
let str_ExstWorkNameNew = NSLocalizedString("str_ExstWorkNameNew", comment:"")
let str_WorkNameNew = NSLocalizedString("str_WorkNameNew", comment:"")
let str_IN = NSLocalizedString("str_IN", comment:"")
let str_InpWorkName = NSLocalizedString("str_InpWorkName", comment:"")
let str_Rename = NSLocalizedString("str_Rename", comment:"")
let str_workout = NSLocalizedString("str_workout", comment:"")
let str_Delete = NSLocalizedString("str_Delete", comment:"")
let str_DelWork = NSLocalizedString("str_DelWork", comment:"")
let str_CrtWork = NSLocalizedString("str_CrtWork", comment:"")
let str_EXERCISE = NSLocalizedString("str_EXERCISE", comment:"")
let str_EXERCISER = NSLocalizedString("str_EXERCISER", comment:"")
let str_EXERCISES = NSLocalizedString("str_EXERCISES", comment:"")
let str_Settings = NSLocalizedString("str_Settings", comment:"")
let str_Reset = NSLocalizedString("str_Reset", comment:"")
let str_ResetAppD = NSLocalizedString("str_ResetAppD", comment:"")
let str_ResetSure = NSLocalizedString("str_ResetSure", comment:"")
let str_kg = NSLocalizedString("str_kg", comment:"")
let str_lb = NSLocalizedString("str_lb", comment:"")
let str_km = NSLocalizedString("str_km", comment:"")
let str_mi = NSLocalizedString("str_mi", comment:"")
let str_Set = NSLocalizedString("str_Set", comment:"")
let str_FeedBack = NSLocalizedString("str_FeedBack", comment:"")
let str_Kilograms = NSLocalizedString("str_Kilograms", comment:"")
let str_Pounds = NSLocalizedString("str_Pounds", comment:"")
let str_Kilometers = NSLocalizedString("str_Kilometers", comment:"")
let str_Miles = NSLocalizedString("str_Miles", comment:"")
let str_WU = NSLocalizedString("str_WU", comment:"")
let str_DU = NSLocalizedString("str_DU", comment:"")
let str_History = NSLocalizedString("str_History", comment:"")
let str_Done = NSLocalizedString("str_Done", comment:"")
let str_AddExercise = NSLocalizedString("str_AddExercise", comment:"")
let str_Loading = NSLocalizedString("str_Loading", comment:"")
let str_Saving = NSLocalizedString("str_Saving", comment:"")
let str_Added = NSLocalizedString("str_Added", comment:"")
let str_Save = NSLocalizedString("str_Save", comment:"")
let str_Today = NSLocalizedString("str_Today", comment:"")
let str_CrCuEx = NSLocalizedString("str_CrCuEx", comment:"")
let str_ExExistName = NSLocalizedString("str_ExExistName", comment:"")
let str_Edit = NSLocalizedString("str_Edit", comment:"")
let str_exercise = NSLocalizedString("str_exercise", comment:"")
let str_Clear = NSLocalizedString("str_Clear", comment:"")
let str_ClrHistory = NSLocalizedString("str_ClrHistory", comment:"")
let str_RnmEx = NSLocalizedString("str_RnmEx", comment:"")
let str_ClrHistoryL = NSLocalizedString("str_ClrHistoryL", comment:"")
let str_BestR = NSLocalizedString("str_BestR", comment:"")
let str_Yesterday = NSLocalizedString("str_Yesterday", comment:"")
let str_Distance = NSLocalizedString("str_Distance", comment:"")
let str_Duration = NSLocalizedString("str_Duration", comment:"")
let str_Date = NSLocalizedString("str_Date", comment:"")
let str_UpdateH = NSLocalizedString("str_UpdateH", comment:"")
let str_Deleting = NSLocalizedString("str_Deleting", comment:"")
let str_NSet = NSLocalizedString("str_NSet", comment:"")
let str_reps = NSLocalizedString("str_reps", comment:"")
let str_hr = NSLocalizedString("str_hr", comment:"")
let str_min = NSLocalizedString("str_min", comment:"")
let str_sec = NSLocalizedString("str_sec", comment:"")
let str_InvalidDate = NSLocalizedString("str_InvalidDate", comment:"")
let str_InvalidDateText = NSLocalizedString("str_InvalidDateText", comment:"")

let str_Saturday = NSLocalizedString("str_Saturday", comment:"")
let str_Sunday = NSLocalizedString("str_Sunday", comment:"")
let str_Monday = NSLocalizedString("str_Monday", comment:"")
let str_Tuesday = NSLocalizedString("str_Tuesday", comment:"")
let str_Wednesday = NSLocalizedString("str_Wednesday", comment:"")
let str_Thursday = NSLocalizedString("str_Thursday", comment:"")
let str_Friday = NSLocalizedString("str_Friday", comment:"")





let str_1  = NSLocalizedString("str_1", comment:"")
let str_2  = NSLocalizedString("str_2", comment:"")
let str_3  = NSLocalizedString("str_3", comment:"")
let str_4  = NSLocalizedString("str_4", comment:"")
let str_5  = NSLocalizedString("str_5", comment:"")
let str_6  = NSLocalizedString("str_6", comment:"")
let str_7  = NSLocalizedString("str_7", comment:"")
let str_8  = NSLocalizedString("str_8", comment:"")
let str_9  = NSLocalizedString("str_9", comment:"")
let str_10 = NSLocalizedString("str_10", comment:"")
let str_11 = NSLocalizedString("str_11", comment:"")
let str_12 = NSLocalizedString("str_12", comment:"")
let str_13 = NSLocalizedString("str_13", comment:"")
let str_14 = NSLocalizedString("str_14", comment:"")
let str_15 = NSLocalizedString("str_15", comment:"")
let str_16 = NSLocalizedString("str_16", comment:"")
let str_17 = NSLocalizedString("str_17", comment:"")
let str_18 = NSLocalizedString("str_18", comment:"")
let str_19 = NSLocalizedString("str_19", comment:"")
let str_20 = NSLocalizedString("str_20", comment:"")
let str_21 = NSLocalizedString("str_21", comment:"")
let str_22 = NSLocalizedString("str_22", comment:"")
let str_23 = NSLocalizedString("str_23", comment:"")
let str_24 = NSLocalizedString("str_24", comment:"")
let str_25 = NSLocalizedString("str_25", comment:"")
let str_26 = NSLocalizedString("str_26", comment:"")
let str_27 = NSLocalizedString("str_27", comment:"")
let str_28 = NSLocalizedString("str_28", comment:"")
let str_29 = NSLocalizedString("str_29", comment:"")
let str_30 = NSLocalizedString("str_30", comment:"")
let str_31 = NSLocalizedString("str_31", comment:"")
let str_32 = NSLocalizedString("str_32", comment:"")
let str_33 = NSLocalizedString("str_33", comment:"")
let str_34 = NSLocalizedString("str_34", comment:"")
let str_35 = NSLocalizedString("str_35", comment:"")
let str_36 = NSLocalizedString("str_36", comment:"")
let str_37 = NSLocalizedString("str_37", comment:"")
let str_38 = NSLocalizedString("str_38", comment:"")
let str_39 = NSLocalizedString("str_39", comment:"")
let str_40 = NSLocalizedString("str_40", comment:"")
let str_41 = NSLocalizedString("str_41", comment:"")
let str_42 = NSLocalizedString("str_42", comment:"")
let str_43 = NSLocalizedString("str_43", comment:"")
let str_44 = NSLocalizedString("str_44", comment:"")
let str_45 = NSLocalizedString("str_45", comment:"")
let str_46 = NSLocalizedString("str_46", comment:"")
let str_47 = NSLocalizedString("str_47", comment:"")
let str_48 = NSLocalizedString("str_48", comment:"")
let str_49 = NSLocalizedString("str_49", comment:"")
let str_50 = NSLocalizedString("str_50", comment:"")
let str_51 = NSLocalizedString("str_51", comment:"")
let str_52 = NSLocalizedString("str_52", comment:"")
let str_53 = NSLocalizedString("str_53", comment:"")
let str_54 = NSLocalizedString("str_54", comment:"")
let str_55 = NSLocalizedString("str_55", comment:"")
let str_56 = NSLocalizedString("str_56", comment:"")
let str_57 = NSLocalizedString("str_57", comment:"")
let str_58 = NSLocalizedString("str_58", comment:"")
let str_59 = NSLocalizedString("str_59", comment:"")
let str_60 = NSLocalizedString("str_60", comment:"")
let str_61 = NSLocalizedString("str_61", comment:"")
let str_62 = NSLocalizedString("str_62", comment:"")
let str_63 = NSLocalizedString("str_63", comment:"")
let str_64 = NSLocalizedString("str_64", comment:"")
let str_65 = NSLocalizedString("str_65", comment:"")
let str_66 = NSLocalizedString("str_66", comment:"")
let str_67 = NSLocalizedString("str_67", comment:"")
let str_68 = NSLocalizedString("str_68", comment:"")
let str_69 = NSLocalizedString("str_69", comment:"")
let str_70 = NSLocalizedString("str_70", comment:"")
let str_71 = NSLocalizedString("str_71", comment:"")
let str_72 = NSLocalizedString("str_72", comment:"")
let str_73 = NSLocalizedString("str_73", comment:"")
let str_74 = NSLocalizedString("str_74", comment:"")
let str_75 = NSLocalizedString("str_75", comment:"")
let str_76 = NSLocalizedString("str_76", comment:"")
let str_77 = NSLocalizedString("str_77", comment:"")
let str_78 = NSLocalizedString("str_78", comment:"")
let str_79 = NSLocalizedString("str_79", comment:"")
let str_80 = NSLocalizedString("str_80", comment:"")
let str_81 = NSLocalizedString("str_81", comment:"")
let str_82 = NSLocalizedString("str_82", comment:"")

let str_83 = NSLocalizedString("str_83", comment:"")
let str_84 = NSLocalizedString("str_84", comment:"")
let str_85 = NSLocalizedString("str_85", comment:"")
let str_86 = NSLocalizedString("str_86", comment:"")
let str_87 = NSLocalizedString("str_87", comment:"")
let str_88 = NSLocalizedString("str_88", comment:"")
let str_89 = NSLocalizedString("str_89", comment:"")
let str_90 = NSLocalizedString("str_90", comment:"")
let str_91 = NSLocalizedString("str_91", comment:"")
let str_92 = NSLocalizedString("str_92", comment:"")
let str_93 = NSLocalizedString("str_93", comment:"")
let str_94 = NSLocalizedString("str_94", comment:"")








